-- Migration 014: Add IDENTITY to property.property_id so inserts auto-generate the id.
-- The column was declared as bare INTEGER PRIMARY KEY with no auto-generation,
-- causing NULL constraint violations when INSERT omits property_id.

-- Set the identity start value past any existing rows.
DO $$
DECLARE
  max_id INTEGER;
BEGIN
  SELECT COALESCE(MAX(property_id), 0) INTO max_id FROM property;
  -- Add identity column generation
  EXECUTE 'ALTER TABLE property ALTER COLUMN property_id ADD GENERATED BY DEFAULT AS IDENTITY';
  -- Restart the sequence past existing rows
  IF max_id > 0 THEN
    EXECUTE format('ALTER TABLE property ALTER COLUMN property_id RESTART WITH %s', max_id + 1);
  END IF;
END $$;
