from __future__ import annotations

from typing import Any, Iterable, Protocol


class AdapterConnection(Protocol):
    def execute(self, sql: str, params: Iterable[Any] | None = None): ...
    def executemany(self, sql: str, seq_of_params: Iterable[Iterable[Any]]): ...
    def executescript(self, sql: str): ...
    def commit(self) -> Any: ...
    def rollback(self) -> Any: ...
    def close(self) -> Any: ...


class DatabaseAdapter(Protocol):
    engine: str

    def connect(self, db_path: str | None = None) -> AdapterConnection: ...
